language: node_js
node_js:
  - 10
before_install:
  - yarn install
scripts:
  - hexo g

deploy:
  provider: releases
  user: $USER
  password: $PWD
  file_glob: true
  file: public/*
  on:
    branch: pages
