language: node_js
node_js:
  - 10
before_install:
  - yarn install
scripts:
  - hexo g

deploy:
  provider: releases
  user: $USER
  password: $PWD
  file: public/*
  skip_cleanup: true
  on:
    branch: pages
